name: testapp1
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher.jpg"
  icons:
    - image_path: "assets/ic_launcher.jpg"
      size: 48x48
    - image_path: "assets/ic_launcher.jpg"
      size: 72x72
    - image_path: "assets/ic_launcher.jpg"
      size: 96x96
    - image_path: "assets/ic_launcher.jpg"
      size: 144x144
    - image_path: "assets/ic_launcher.jpg"
      size: 192x192
